### ISSUE TITLE
check for monorepo packages may return false positives

### ISSUE THREAD

**Issue by jenniferarnesen** [dhis2/deploy-build#11]
The test on lines 166 and 167 of deploy_build.sh does a name comparison based on the name of the root package, which could return false positives. This issue is currently blocking some bug fixes in analytics apps due to the new package named "d2-ui-analytics", which is not in "d2-ui".

One suggestion for a fix is to get the list of monorepo sub-packages and use that for checking the dependencies. Something like the following (but improved bc I can't bash scripting):

```
#!/usr/bin/env bash

internalPackages=()

for d in packages/* ; do
    packageName=`jq -r '.name' $d/package.json`
    internalPackages+=( "$packageName" )
done

#test assumes the root package is d2-ui
testNames=(@dhis2/d2-ui-translation-dialog @dhis2/d2-ui-analytics)

for g in "${testNames[@]}" ; do
    if [[ " ${internalPackages[@]} " =~ " ${g} " ]]; then
        echo "${g} is internal"
    else
        echo "${g} is not internal"
    fi
done
```

**Comment by varl** [comment]
I will take a look if we can solve the assumption that deploy-build makes about d2-ui. In the meantime, I don't think that d2-ui-analytics actually needs to use deploy-build (https://github.com/dhis2/d2-ui-analytics/pull/14)?

**Comment by varl** [comment]
I poked around with your suggestions and the one that was the easiest to integrate into the house of cards was looking for the `0.0.0-PLACEHOLDER` and switching that out with the proper version leaving the others intact.

This works nicely: https://travis-ci.com/dhis2/d2-ui/builds/108344589
